---
title: "Predicting Olympic Success"
subtitle: "Analyzing the Correlation Between Medal Count and Socioeconomic Factors"
author: Hannah Hodge, Jedidiah Bechtel, Sandy Alksninis, Aedan Bayhan
date: September 22, 2024
format: 
  html:
    toc: true 
    toc-location: right
    theme: flatly
    self-contained: true
---

```{r}
#| label: setup 
#| include: false

# Load libraries and settings here
library(tidyverse)
library(here)

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = "figs/", # Folder where rendered plots are saved
  fig.width = 7.252, # Default plot width
  fig.height = 4, # Default plot height
  fig.retina = 3 # For better plot resolution
)

# Put any other "global" settings here, e.g. a ggplot theme:
theme_set(theme_bw(base_size = 20))

# Write code below here to load any data used in project

```

### Reasearch Question

Over the past 50 years, what are the correlations between the medal count for the Olympics and GDP per Capita, population, cultural emphasis on sports, and government funding? What about new sports introduced to the Olympics, do they follow the same trends? If these factors correlate, is it possible to predict future medal counts for specific countries based on this data? Can a true winner of the Olympics be determined?

### Introduction

Over the past 50 years, The United States of America has seemingly run away with the total medal count at the Summer Olympics. Most attribute this to the sheer number of athletes that comprise the United States delegation every four years, others gaze at the government's funding of athletes, and some even ponder if patriotism plays a role in the country's success. To address why the United States finds so much success we asked the question: Over the past 50 years, what are the correlations between the medal count for the Olympics and GDP per Capita, population, cultural emphasis on sports, and government funding? I hope not only to solve the riddle of what makes a country successful but also to possibly predict the medal counts in the coming Olympic games. The significance of our question is that if we can identify which factors directly correlate to better Olympic performances we might also be able to minimize their inputs effectively leveling the playing field for countries trailing in the medal count as the Olympics should be about athletic prowess, not a country's politics. Not only can we level the playing field, but we can also advise countries looking to improve their performance. Finally, Olympic success is been measured by how many gold medals a country wins and if there is a tie how many total medals that country has. What if, based on our findings, this metric of success is not just, we could provide insight into determining how Olympic success should truly be judged. 


### Sources 

#### [Medal table at the Paris 2024 Olympic Summer Games](https://www.statista.com/statistics/1483973/medals-olympic-summer-games-paris-2024/)

This source is from a data and statistics website called Statista. This website complies data into readable tables and charts. The original data is from olympic.org, which is the official Olympic website. This source provides reliable and up-to-date information on Olympic medal counts and performance statistics. This data will help analyze trends and patterns in Olympic results over time. The only concern is that this website generates charts that can be misleading if not examined carefully.

#### Olympism in Action: Trends and Perspectives

Olympism in Action: Trends and Perspectives is a report published by the International Olympic Committee (IOC). The IOC is a global organization that is a collaboration between many stakeholders for the Olympics. It is a trustworthy source that offers factsheets, annual reports, and public media for analysis. 

#### [The Conversation](https://theconversation.com/us/topics/olympic-games-6108)

This website offers a wide variety of articles and journals about the Olympics. It is not trustworthy, as many of the articles are opinion pieces. However, there are many insightful ideas that are discussed and worth thought in answering some questions. This source can be used as inspiration rather than drawing data from it. 

### Results 

Based on a preliminary look at datasets and preexisting knowledge we predict that GDP per Capita and population will have the strongest correlation with Olympic medal success. Due to the ever-changing nature of GDP per Capita, we think that one way to standardize this metric is by ranking it in terms of most to least. This is because, in times of financial crisis, the GDP per capita might fall yet Olympic success still could rise. This is because while the GDP fell, it did not decrease as much as other countries. There might also be some problems with measuring overall Olympic success purely off medal count because some countries such as the United States and the USSR each boycotted games meaning their medal count would be effectively zero. We plan to use bar charts, box plots as well as correlation matrices to explore our data and get a sense of how it is distributed. After the initial exploration, we will utilize scatterplots to visually see if our data is correlated or not. We might even be able to use linear regression on some of our data if it is normally distributed to generate a predictive model based on our factors of how a country might do at the next Olympics. Our results will directly answer our question which essentially asks: What makes a country so dominant at the Olympics? And is there a true winner of the Olympics?


### Attribution

- Hannah Hodge, Jedidiah Bechtel, Sandy Alksninis, and Aedan Bayhan researched and wrote the research question. 

- Jedidiah Bechtel wrote the Introduction and Results portion

- Hannah Hodge wrote the Sources section as well as organized the project files and put the report into R














